# Use an official Ubuntu base image
FROM ubuntu:latest

# Avoid prompts from apt
ENV DEBIAN_FRONTEND=noninteractive

# Install curl
RUN apt-get update && apt-get install -y curl

# Run the Kuzco installation command
RUN curl -fsSL https://kuzco.xyz/install.sh | sh

# (Optional) Define a command for the container to run on startup, such as starting Kuzco
# CMD ["kuzco", "some", "arguments"]
CMD ["tail", "-f", "/dev/null"]
# CMD ["kuzco", "init"]
